import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Course from './models/Course.js';

dotenv.config();

const courses = [
  // Original courses (keeping non-Coursera ones)
  {
    title: 'CS50: Introduction to Computer Science',
    description: 'Harvard University\'s introduction to computer science and programming. Learn to think algorithmically and solve problems efficiently. Topics include abstraction, algorithms, data structures, software engineering, and web development. Languages include C, Python, SQL, JavaScript, CSS, and HTML.',
    platform: 'edX',
    category: 'Technology',
    subcategory: 'Computer Science',
    difficulty: 'Beginner',
    duration: '11 weeks',
    language: 'English',
    courseUrl: 'https://www.edx.org/learn/computer-science/harvard-university-cs50-s-introduction-to-computer-science',
    instructor: 'David J. Malan',
    rating: 4.9,
    studentsEnrolled: '4M+',
    tags: ['Computer Science', 'Programming', 'C', 'Python', 'JavaScript'],
    skills: ['Programming', 'Problem Solving', 'Algorithms', 'Web Development'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'The Complete 2024 Web Development Bootcamp',
    description: 'Become a Full-Stack Web Developer with just ONE course. HTML, CSS, Javascript, Node, React, PostgreSQL, Web3 and DApps. This comprehensive bootcamp covers frontend and backend development.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Web Development',
    difficulty: 'Beginner',
    duration: '65 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=nu_pCVPKzTk',
    instructor: 'freeCodeCamp.org',
    rating: 4.9,
    studentsEnrolled: '500K+',
    tags: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'],
    skills: ['Frontend Development', 'Backend Development', 'Full Stack'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Data Science Professional Certificate',
    description: 'Kickstart your career in data science. Master Python, analyze data, create visualizations, and build machine learning models. No prior experience needed. This Professional Certificate will give you the technical skills to become job-ready.',
    platform: 'edX',
    category: 'Technology',
    subcategory: 'Data Science',
    difficulty: 'Intermediate',
    duration: '9 months',
    language: 'English',
    courseUrl: 'https://www.edx.org/professional-certificate/ibm-data-science',
    instructor: 'IBM',
    rating: 4.5,
    studentsEnrolled: '400K+',
    tags: ['Data Science', 'Python', 'Machine Learning', 'Data Visualization'],
    skills: ['Data Analysis', 'Python', 'SQL', 'Machine Learning'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },
  {
    title: 'Introduction to Cybersecurity',
    description: 'Learn cybersecurity basics and protect yourself online. Explore the cybersecurity landscape and understand how to protect personal and organizational assets. Topics include cryptography, network security, and ethical hacking.',
    platform: 'edX',
    category: 'Technology',
    subcategory: 'Cybersecurity',
    difficulty: 'Beginner',
    duration: '6 weeks',
    language: 'English',
    courseUrl: 'https://www.edx.org/learn/cybersecurity/the-university-of-washington-introduction-to-cybersecurity',
    instructor: 'University of Washington',
    rating: 4.6,
    studentsEnrolled: '150K+',
    tags: ['Cybersecurity', 'Network Security', 'Ethical Hacking', 'Cryptography'],
    skills: ['Security Fundamentals', 'Threat Detection', 'Risk Assessment'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },

  // NEW FREE COURSES FROM VARIOUS PLATFORMS

  // freeCodeCamp Certifications (YouTube + Platform)
  {
    title: 'freeCodeCamp Responsive Web Design Certification',
    description: 'Learn HTML, CSS, Flexbox, Grid, and Responsive Design principles. Build 5 projects to earn a free certificate. Completely free with no ads and includes hands-on projects that you can add to your portfolio.',
    platform: 'freeCodeCamp',
    category: 'Technology',
    subcategory: 'Web Development',
    difficulty: 'Beginner',
    duration: '300 hours',
    language: 'English',
    courseUrl: 'https://www.freecodecamp.org/learn/2022/responsive-web-design/',
    instructor: 'freeCodeCamp.org',
    rating: 4.8,
    studentsEnrolled: '2M+',
    tags: ['HTML', 'CSS', 'Responsive Design', 'Flexbox', 'CSS Grid'],
    skills: ['HTML5', 'CSS3', 'Responsive Design', 'Web Accessibility'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'JavaScript Algorithms and Data Structures',
    description: 'Learn JavaScript fundamentals including variables, arrays, objects, loops, and functions. Then move on to Object Oriented Programming, Functional Programming, algorithmic thinking, and working with local storage. Free certificate upon completion.',
    platform: 'freeCodeCamp',
    category: 'Technology',
    subcategory: 'Programming',
    difficulty: 'Beginner',
    duration: '300 hours',
    language: 'English',
    courseUrl: 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/',
    instructor: 'freeCodeCamp.org',
    rating: 4.9,
    studentsEnrolled: '1.5M+',
    tags: ['JavaScript', 'Algorithms', 'Data Structures', 'ES6', 'OOP'],
    skills: ['JavaScript', 'Problem Solving', 'Algorithms', 'Functional Programming'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Front End Development Libraries',
    description: 'Learn to build powerful interactive applications with popular libraries like React, Redux, Bootstrap, jQuery, and Sass. Build 5 projects to earn your free certification.',
    platform: 'freeCodeCamp',
    category: 'Technology',
    subcategory: 'Web Development',
    difficulty: 'Intermediate',
    duration: '300 hours',
    language: 'English',
    courseUrl: 'https://www.freecodecamp.org/learn/front-end-development-libraries/',
    instructor: 'freeCodeCamp.org',
    rating: 4.8,
    studentsEnrolled: '800K+',
    tags: ['React', 'Redux', 'Bootstrap', 'jQuery', 'Sass'],
    skills: ['React', 'State Management', 'UI Frameworks', 'Frontend Development'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },

  // YouTube Comprehensive Courses
  {
    title: 'Python for Beginners - Full Course',
    description: 'Complete Python tutorial for absolute beginners. Learn Python basics, OOP, file handling, and build real projects. This 4+ hour course covers everything you need to start programming in Python.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Programming',
    difficulty: 'Beginner',
    duration: '4.5 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=rfscVS0vtbw',
    instructor: 'Programming with Mosh',
    rating: 4.9,
    studentsEnrolled: '10M+',
    tags: ['Python', 'Programming', 'OOP', 'Beginners'],
    skills: ['Python Programming', 'Object-Oriented Programming', 'Problem Solving'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'React Course - Beginner\'s Tutorial',
    description: 'Learn React from scratch. Build modern web applications with hooks, context API, and best practices. Perfect for beginners who know basic JavaScript.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Web Development',
    difficulty: 'Beginner',
    duration: '12 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=bMknfKXIFA8',
    instructor: 'freeCodeCamp.org',
    rating: 4.9,
    studentsEnrolled: '5M+',
    tags: ['React', 'JavaScript', 'Hooks', 'Frontend', 'Web Development'],
    skills: ['React', 'Component Architecture', 'State Management', 'Hooks'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Data Structures and Algorithms Full Course',
    description: 'Master data structures and algorithms with clear explanations and coding examples. Essential for technical interviews and competitive programming. Covers arrays, linked lists, trees, graphs, sorting, searching, and more.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Computer Science',
    difficulty: 'Intermediate',
    duration: '8 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=8hly31xKli0',
    instructor: 'freeCodeCamp.org',
    rating: 4.8,
    studentsEnrolled: '3M+',
    tags: ['Data Structures', 'Algorithms', 'DSA', 'Problem Solving', 'Interviews'],
    skills: ['Data Structures', 'Algorithms', 'Problem Solving', 'Technical Interviews'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Machine Learning Course - Full 2024',
    description: 'Comprehensive machine learning course covering supervised learning, unsupervised learning, neural networks, and deep learning. Includes hands-on Python projects.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Artificial Intelligence',
    difficulty: 'Intermediate',
    duration: '11 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=i_LwzRVP7bg',
    instructor: 'freeCodeCamp.org',
    rating: 4.9,
    studentsEnrolled: '2M+',
    tags: ['Machine Learning', 'AI', 'Python', 'Neural Networks', 'Deep Learning'],
    skills: ['Machine Learning', 'Data Science', 'Neural Networks', 'Python'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'SQL Tutorial - Full Database Course',
    description: 'Learn SQL and database management from scratch. Perfect for beginners. Covers database design, queries, joins, aggregations, and advanced SQL concepts.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Database',
    difficulty: 'Beginner',
    duration: '4 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=HXV3zeQKqGY',
    instructor: 'freeCodeCamp.org',
    rating: 4.8,
    studentsEnrolled: '8M+',
    tags: ['SQL', 'Database', 'MySQL', 'PostgreSQL', 'Data Management'],
    skills: ['SQL', 'Database Design', 'Query Optimization', 'Data Management'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Git and GitHub for Beginners',
    description: 'Learn version control with Git and GitHub. Essential for all developers. Covers repositories, commits, branches, merging, pull requests, and collaboration workflows.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Development Tools',
    difficulty: 'Beginner',
    duration: '1 hour',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=RGOj5yH7evk',
    instructor: 'freeCodeCamp.org',
    rating: 4.9,
    studentsEnrolled: '6M+',
    tags: ['Git', 'GitHub', 'Version Control', 'DevOps', 'Collaboration'],
    skills: ['Git', 'Version Control', 'GitHub', 'Collaboration'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },
  {
    title: 'Node.js and Express.js - Full Course',
    description: 'Learn backend development with Node.js and Express. Build RESTful APIs and full-stack applications. Covers routing, middleware, authentication, and database integration.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Backend Development',
    difficulty: 'Intermediate',
    duration: '8 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=Oe421EPjeBE',
    instructor: 'freeCodeCamp.org',
    rating: 4.8,
    studentsEnrolled: '2M+',
    tags: ['Node.js', 'Express', 'Backend', 'API', 'JavaScript'],
    skills: ['Node.js', 'Express', 'RESTful APIs', 'Backend Development'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },

  // GeeksforGeeks Courses
  {
    title: 'DSA to Development - Complete Guide',
    description: 'GeeksforGeeks comprehensive guide covering Data Structures, Algorithms, and development fundamentals. Free articles, tutorials, and practice problems to master DSA.',
    platform: 'GeeksforGeeks',
    category: 'Technology',
    subcategory: 'Computer Science',
    difficulty: 'Beginner',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://www.geeksforgeeks.org/dsa-tutorial-learn-data-structures-and-algorithms/',
    instructor: 'GeeksforGeeks',
    rating: 4.7,
    studentsEnrolled: '5M+',
    tags: ['DSA', 'Data Structures', 'Algorithms', 'Problem Solving'],
    skills: ['Data Structures', 'Algorithms', 'Competitive Programming'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Java Programming Complete Guide',
    description: 'Learn Java from basics to advanced concepts. Covers OOP, collections, multithreading, and Java frameworks. Free comprehensive tutorials with examples and exercises.',
    platform: 'GeeksforGeeks',
    category: 'Technology',
    subcategory: 'Programming',
    difficulty: 'Beginner',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://www.geeksforgeeks.org/java/',
    instructor: 'GeeksforGeeks',
    rating: 4.6,
    studentsEnrolled: '3M+',
    tags: ['Java', 'OOP', 'Programming', 'Backend Development'],
    skills: ['Java Programming', 'Object-Oriented Programming', 'Software Development'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },

  // Scaler Topics
  {
    title: 'C++ Programming Complete Tutorial',
    description: 'Master C++ from basics to advanced. Learn syntax, OOP, STL, memory management, and competitive programming. Comprehensive free tutorials with practice problems.',
    platform: 'Scaler',
    category: 'Technology',
    subcategory: 'Programming',
    difficulty: 'Beginner',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://www.scaler.com/topics/cpp/',
    instructor: 'Scaler Topics',
    rating: 4.7,
    studentsEnrolled: '500K+',
    tags: ['C++', 'Programming', 'OOP', 'STL', 'Competitive Programming'],
    skills: ['C++ Programming', 'Object-Oriented Programming', 'Data Structures'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },
  {
    title: 'Data Structures Tutorial',
    description: 'Learn all essential data structures including arrays, linked lists, stacks, queues, trees, graphs, and hash tables. Free tutorials with visualizations and coding examples.',
    platform: 'Scaler',
    category: 'Technology',
    subcategory: 'Computer Science',
    difficulty: 'Beginner',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://www.scaler.com/topics/data-structures/',
    instructor: 'Scaler Topics',
    rating: 4.8,
    studentsEnrolled: '800K+',
    tags: ['Data Structures', 'Algorithms', 'Programming', 'Problem Solving'],
    skills: ['Data Structures', 'Problem Solving', 'Algorithm Design'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Python Tutorial - Complete Guide',
    description: 'Comprehensive Python tutorial covering basics to advanced topics. Learn Python syntax, data structures, OOP, file handling, and popular libraries like NumPy and Pandas.',
    platform: 'Scaler',
    category: 'Technology',
    subcategory: 'Programming',
    difficulty: 'Beginner',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://www.scaler.com/topics/python/',
    instructor: 'Scaler Topics',
    rating: 4.7,
    studentsEnrolled: '1M+',
    tags: ['Python', 'Programming', 'Data Science', 'OOP'],
    skills: ['Python Programming', 'Data Analysis', 'Problem Solving'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },

  // edX Free Certificate Courses
  {
    title: 'CS50\'s Web Programming with Python and JavaScript',
    description: 'Learn to design and implement web applications using Python, JavaScript, and SQL. Topics include database design, scalability, security, and user experience. Free certificate available.',
    platform: 'edX',
    category: 'Technology',
    subcategory: 'Web Development',
    difficulty: 'Intermediate',
    duration: '12 weeks',
    language: 'English',
    courseUrl: 'https://www.edx.org/learn/web-development/harvard-university-cs50-s-web-programming-with-python-and-javascript',
    instructor: 'Harvard University',
    rating: 4.9,
    studentsEnrolled: '500K+',
    tags: ['Web Development', 'Python', 'JavaScript', 'Django', 'SQL'],
    skills: ['Full Stack Development', 'Python', 'JavaScript', 'Database Design'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'CS50\'s Introduction to Artificial Intelligence with Python',
    description: 'Explore the concepts and algorithms at the foundation of modern AI. Learn graph search, classification, optimization, reinforcement learning, and neural networks using Python.',
    platform: 'edX',
    category: 'Technology',
    subcategory: 'Artificial Intelligence',
    difficulty: 'Intermediate',
    duration: '7 weeks',
    language: 'English',
    courseUrl: 'https://www.edx.org/learn/artificial-intelligence/harvard-university-cs50-s-introduction-to-artificial-intelligence-with-python',
    instructor: 'Harvard University',
    rating: 4.8,
    studentsEnrolled: '600K+',
    tags: ['AI', 'Machine Learning', 'Python', 'Neural Networks', 'Deep Learning'],
    skills: ['Artificial Intelligence', 'Machine Learning', 'Python', 'Algorithm Design'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Introduction to Linux',
    description: 'Learn Linux fundamentals including command line, file systems, and system administration. Essential for developers and IT professionals. Free certificate upon completion.',
    platform: 'edX',
    category: 'Technology',
    subcategory: 'Operating Systems',
    difficulty: 'Beginner',
    duration: '14 weeks',
    language: 'English',
    courseUrl: 'https://www.edx.org/learn/linux/the-linux-foundation-introduction-to-linux',
    instructor: 'The Linux Foundation',
    rating: 4.6,
    studentsEnrolled: '1M+',
    tags: ['Linux', 'Command Line', 'System Administration', 'DevOps'],
    skills: ['Linux', 'Command Line', 'System Administration', 'Shell Scripting'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },

  // Additional YouTube Specialized Courses
  {
    title: 'Docker Tutorial for Beginners',
    description: 'Learn Docker containerization from scratch. Covers Docker basics, images, containers, Docker Compose, and deploying applications. Essential for modern DevOps.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'DevOps',
    difficulty: 'Beginner',
    duration: '3 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=fqMOX6JJhGo',
    instructor: 'freeCodeCamp.org',
    rating: 4.8,
    studentsEnrolled: '2M+',
    tags: ['Docker', 'Containers', 'DevOps', 'Deployment', 'Cloud'],
    skills: ['Docker', 'Containerization', 'DevOps', 'Deployment'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },
  {
    title: 'AWS Certified Cloud Practitioner Course',
    description: 'Prepare for AWS Cloud Practitioner certification. Learn cloud concepts, AWS services, security, architecture, and pricing. Free comprehensive course covering all exam topics.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Cloud Computing',
    difficulty: 'Beginner',
    duration: '14 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=SOTamWNgDKc',
    instructor: 'freeCodeCamp.org',
    rating: 4.9,
    studentsEnrolled: '1M+',
    tags: ['AWS', 'Cloud Computing', 'Certification', 'DevOps', 'Cloud Architecture'],
    skills: ['Cloud Computing', 'AWS Services', 'Cloud Architecture', 'Security'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Ethical Hacking - Full Course',
    description: 'Learn ethical hacking and penetration testing. Covers reconnaissance, scanning, exploitation, and security best practices. Understand cybersecurity from an attacker\'s perspective.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Cybersecurity',
    difficulty: 'Intermediate',
    duration: '15 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=3Kq1MIfTWCE',
    instructor: 'freeCodeCamp.org',
    rating: 4.7,
    studentsEnrolled: '1.5M+',
    tags: ['Ethical Hacking', 'Cybersecurity', 'Penetration Testing', 'Security'],
    skills: ['Ethical Hacking', 'Penetration Testing', 'Network Security', 'Vulnerability Assessment'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },
  {
    title: 'Flutter Course - Build iOS and Android Apps',
    description: 'Learn Flutter and Dart to build beautiful cross-platform mobile applications. Create apps for iOS and Android with a single codebase. Includes real-world projects.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Mobile Development',
    difficulty: 'Beginner',
    duration: '37 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=VPvVD8t02U8',
    instructor: 'freeCodeCamp.org',
    rating: 4.8,
    studentsEnrolled: '800K+',
    tags: ['Flutter', 'Dart', 'Mobile Development', 'iOS', 'Android'],
    skills: ['Flutter', 'Mobile Development', 'Dart Programming', 'UI Design'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'TypeScript Full Course',
    description: 'Master TypeScript from basics to advanced concepts. Learn type systems, interfaces, generics, decorators, and how to use TypeScript with React and Node.js.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Programming',
    difficulty: 'Intermediate',
    duration: '8 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=30LWjhZzg50',
    instructor: 'freeCodeCamp.org',
    rating: 4.8,
    studentsEnrolled: '1M+',
    tags: ['TypeScript', 'JavaScript', 'Programming', 'Web Development'],
    skills: ['TypeScript', 'Type Systems', 'JavaScript', 'Software Development'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },
  {
    title: 'MongoDB Complete Guide',
    description: 'Learn MongoDB database from scratch. Covers CRUD operations, data modeling, aggregation, indexing, and building full-stack applications with MongoDB.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Database',
    difficulty: 'Beginner',
    duration: '8 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=-56x56UppqQ',
    instructor: 'freeCodeCamp.org',
    rating: 4.7,
    studentsEnrolled: '500K+',
    tags: ['MongoDB', 'NoSQL', 'Database', 'Backend', 'MERN Stack'],
    skills: ['MongoDB', 'NoSQL', 'Database Design', 'Backend Development'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },
  {
    title: 'Next.js Full Course',
    description: 'Learn Next.js, the React framework for production. Build server-side rendered and statically generated applications. Covers routing, API routes, deployment, and more.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Web Development',
    difficulty: 'Intermediate',
    duration: '11 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=843nec-IvW0',
    instructor: 'freeCodeCamp.org',
    rating: 4.9,
    studentsEnrolled: '600K+',
    tags: ['Next.js', 'React', 'SSR', 'Web Development', 'Full Stack'],
    skills: ['Next.js', 'React', 'Server-Side Rendering', 'Full Stack Development'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },

  // BUSINESS & MANAGEMENT COURSES
  {
    title: 'Introduction to Business Management',
    description: 'Learn fundamental business concepts including planning, organizing, leading, and controlling. Covers organizational structure, decision-making, and business strategy. Perfect for aspiring entrepreneurs and managers.',
    platform: 'Saylor Academy',
    category: 'Business',
    subcategory: 'Management',
    difficulty: 'Beginner',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://learn.saylor.org/course/view.php?id=92',
    instructor: 'Saylor Academy',
    rating: 4.6,
    studentsEnrolled: '200K+',
    tags: ['Business Management', 'Leadership', 'Strategy', 'Organization'],
    skills: ['Management', 'Leadership', 'Strategic Thinking', 'Decision Making'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Principles of Marketing',
    description: 'Comprehensive marketing course covering consumer behavior, market research, product development, pricing strategies, distribution, and promotional strategies. Learn to create effective marketing plans.',
    platform: 'Saylor Academy',
    category: 'Business',
    subcategory: 'Marketing',
    difficulty: 'Beginner',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://learn.saylor.org/course/view.php?id=95',
    instructor: 'Saylor Academy',
    rating: 4.7,
    studentsEnrolled: '150K+',
    tags: ['Marketing', 'Consumer Behavior', 'Market Research', 'Branding'],
    skills: ['Marketing Strategy', 'Market Research', 'Consumer Analysis', 'Brand Management'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Financial Accounting',
    description: 'Learn the fundamentals of financial accounting including financial statements, balance sheets, income statements, cash flow, and accounting principles. Essential for business students and professionals.',
    platform: 'Saylor Academy',
    category: 'Business',
    subcategory: 'Accounting',
    difficulty: 'Beginner',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://learn.saylor.org/course/view.php?id=75',
    instructor: 'Saylor Academy',
    rating: 4.5,
    studentsEnrolled: '180K+',
    tags: ['Accounting', 'Finance', 'Financial Statements', 'Business'],
    skills: ['Financial Accounting', 'Financial Analysis', 'Bookkeeping', 'Financial Reporting'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },
  {
    title: 'Entrepreneurship',
    description: 'Discover how to start and grow a successful business. Learn about opportunity recognition, business planning, funding strategies, marketing, and scaling. Includes real-world case studies.',
    platform: 'Saylor Academy',
    category: 'Business',
    subcategory: 'Entrepreneurship',
    difficulty: 'Beginner',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://learn.saylor.org/course/view.php?id=91',
    instructor: 'Saylor Academy',
    rating: 4.8,
    studentsEnrolled: '120K+',
    tags: ['Entrepreneurship', 'Startup', 'Business Planning', 'Innovation'],
    skills: ['Business Planning', 'Innovation', 'Venture Capital', 'Business Development'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },

  // ECONOMICS COURSES
  {
    title: 'Principles of Microeconomics',
    description: 'Understand how individuals and firms make economic decisions. Covers supply and demand, market equilibrium, elasticity, consumer theory, production costs, and market structures.',
    platform: 'Saylor Academy',
    category: 'Business',
    subcategory: 'Economics',
    difficulty: 'Beginner',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://learn.saylor.org/course/view.php?id=7',
    instructor: 'Saylor Academy',
    rating: 4.6,
    studentsEnrolled: '250K+',
    tags: ['Economics', 'Microeconomics', 'Supply and Demand', 'Market Theory'],
    skills: ['Economic Analysis', 'Market Analysis', 'Critical Thinking', 'Quantitative Reasoning'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Principles of Macroeconomics',
    description: 'Explore how national economies function. Learn about GDP, inflation, unemployment, fiscal policy, monetary policy, international trade, and economic growth.',
    platform: 'Saylor Academy',
    category: 'Business',
    subcategory: 'Economics',
    difficulty: 'Beginner',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://learn.saylor.org/course/view.php?id=8',
    instructor: 'Saylor Academy',
    rating: 4.7,
    studentsEnrolled: '200K+',
    tags: ['Economics', 'Macroeconomics', 'GDP', 'Monetary Policy', 'Fiscal Policy'],
    skills: ['Economic Policy', 'Fiscal Analysis', 'Economic Forecasting', 'International Economics'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },

  // PSYCHOLOGY COURSES
  {
    title: 'Introduction to Psychology',
    description: 'Explore the scientific study of mind and behavior. Topics include brain function, perception, learning, memory, cognition, development, personality, social psychology, and mental health.',
    platform: 'Saylor Academy',
    category: 'Personal Development',
    subcategory: 'Psychology',
    difficulty: 'Beginner',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://learn.saylor.org/course/view.php?id=48',
    instructor: 'Saylor Academy',
    rating: 4.8,
    studentsEnrolled: '300K+',
    tags: ['Psychology', 'Mental Health', 'Human Behavior', 'Cognitive Science'],
    skills: ['Psychology', 'Critical Thinking', 'Research Methods', 'Human Behavior Analysis'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Social Psychology',
    description: 'Study how people think about, influence, and relate to one another. Covers attitudes, persuasion, conformity, group dynamics, prejudice, aggression, and prosocial behavior.',
    platform: 'Saylor Academy',
    category: 'Personal Development',
    subcategory: 'Psychology',
    difficulty: 'Intermediate',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://learn.saylor.org/course/view.php?id=49',
    instructor: 'Saylor Academy',
    rating: 4.7,
    studentsEnrolled: '150K+',
    tags: ['Social Psychology', 'Group Dynamics', 'Human Behavior', 'Social Influence'],
    skills: ['Social Analysis', 'Communication', 'Empathy', 'Critical Thinking'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },

  // MIT OpenCourseWare Courses
  {
    title: 'Introduction to Algorithms (MIT)',
    description: 'MIT\'s legendary algorithms course covering sorting, searching, graph algorithms, dynamic programming, and complexity theory. Includes video lectures from renowned professors. Advanced but accessible.',
    platform: 'MIT OpenCourseWare',
    category: 'Technology',
    subcategory: 'Computer Science',
    difficulty: 'Advanced',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/',
    instructor: 'MIT',
    rating: 4.9,
    studentsEnrolled: '1M+',
    tags: ['Algorithms', 'Data Structures', 'Computer Science', 'MIT'],
    skills: ['Algorithm Design', 'Computational Complexity', 'Problem Solving', 'Mathematical Analysis'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Introduction to Computer Science and Programming (MIT)',
    description: 'MIT\'s intro CS course using Python. Learn computational thinking, problem-solving, and programming fundamentals. Perfect for beginners with no prior programming experience.',
    platform: 'MIT OpenCourseWare',
    category: 'Technology',
    subcategory: 'Computer Science',
    difficulty: 'Beginner',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/',
    instructor: 'MIT',
    rating: 4.8,
    studentsEnrolled: '800K+',
    tags: ['Python', 'Programming', 'Computer Science', 'MIT', 'Beginners'],
    skills: ['Python Programming', 'Computational Thinking', 'Problem Solving', 'Algorithm Design'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Linear Algebra (MIT)',
    description: 'Professor Gilbert Strang\'s famous linear algebra course. Essential for machine learning, data science, and engineering. Covers matrices, vector spaces, eigenvalues, and applications.',
    platform: 'MIT OpenCourseWare',
    category: 'Technology',
    subcategory: 'Mathematics',
    difficulty: 'Intermediate',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/',
    instructor: 'Gilbert Strang, MIT',
    rating: 4.9,
    studentsEnrolled: '2M+',
    tags: ['Linear Algebra', 'Mathematics', 'Machine Learning', 'MIT'],
    skills: ['Linear Algebra', 'Matrix Operations', 'Mathematical Analysis', 'Problem Solving'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Artificial Intelligence (MIT)',
    description: 'Comprehensive AI course from MIT covering search algorithms, knowledge representation, machine learning, and robotics. Includes lectures, assignments, and projects.',
    platform: 'MIT OpenCourseWare',
    category: 'Technology',
    subcategory: 'Artificial Intelligence',
    difficulty: 'Advanced',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://ocw.mit.edu/courses/6-034-artificial-intelligence-fall-2010/',
    instructor: 'MIT',
    rating: 4.8,
    studentsEnrolled: '500K+',
    tags: ['Artificial Intelligence', 'Machine Learning', 'Robotics', 'MIT'],
    skills: ['AI', 'Machine Learning', 'Problem Solving', 'Algorithm Design'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Calculus 1: Single Variable Calculus (MIT)',
    description: 'MIT\'s foundational calculus course covering limits, derivatives, integrals, and applications. Essential for STEM students. Includes comprehensive video lectures and problem sets.',
    platform: 'MIT OpenCourseWare',
    category: 'Technology',
    subcategory: 'Mathematics',
    difficulty: 'Intermediate',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/',
    instructor: 'MIT',
    rating: 4.7,
    studentsEnrolled: '600K+',
    tags: ['Calculus', 'Mathematics', 'STEM', 'MIT'],
    skills: ['Calculus', 'Mathematical Analysis', 'Problem Solving', 'Quantitative Reasoning'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },

  // COMMUNICATION & SOFT SKILLS
  {
    title: 'Business Communication',
    description: 'Master professional communication skills including writing emails, reports, presentations, and interpersonal communication. Learn to communicate effectively in business contexts.',
    platform: 'Saylor Academy',
    category: 'Personal Development',
    subcategory: 'Communication',
    difficulty: 'Beginner',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://learn.saylor.org/course/view.php?id=115',
    instructor: 'Saylor Academy',
    rating: 4.6,
    studentsEnrolled: '100K+',
    tags: ['Communication', 'Business Writing', 'Presentation Skills', 'Professional Skills'],
    skills: ['Business Communication', 'Writing', 'Public Speaking', 'Professional Communication'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },
  {
    title: 'Critical Thinking and Problem Solving',
    description: 'Develop analytical and critical thinking skills. Learn to analyze arguments, identify logical fallacies, solve complex problems, and make better decisions.',
    platform: 'Alison',
    category: 'Personal Development',
    subcategory: 'Critical Thinking',
    difficulty: 'Beginner',
    duration: '2-3 hours',
    language: 'English',
    courseUrl: 'https://alison.com/course/critical-thinking-and-problem-solving',
    instructor: 'Alison',
    rating: 4.5,
    studentsEnrolled: '250K+',
    tags: ['Critical Thinking', 'Problem Solving', 'Logic', 'Decision Making'],
    skills: ['Critical Thinking', 'Logical Reasoning', 'Problem Solving', 'Decision Making'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },

  // ADDITIONAL DIVERSE COURSES
  {
    title: 'Environmental Science',
    description: 'Study environmental systems, sustainability, climate change, ecology, and conservation. Learn about environmental challenges and solutions for a sustainable future.',
    platform: 'Saylor Academy',
    category: 'Science',
    subcategory: 'Environmental Science',
    difficulty: 'Beginner',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://learn.saylor.org/course/view.php?id=40',
    instructor: 'Saylor Academy',
    rating: 4.7,
    studentsEnrolled: '80K+',
    tags: ['Environmental Science', 'Sustainability', 'Climate Change', 'Ecology'],
    skills: ['Environmental Analysis', 'Sustainability', 'Scientific Thinking', 'Research'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },
  {
    title: 'Statistics for Data Science',
    description: 'Learn statistical concepts essential for data science including probability, hypothesis testing, regression, and statistical inference. Practical applications for data analysis.',
    platform: 'Saylor Academy',
    category: 'Technology',
    subcategory: 'Data Science',
    difficulty: 'Intermediate',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://learn.saylor.org/course/view.php?id=30',
    instructor: 'Saylor Academy',
    rating: 4.6,
    studentsEnrolled: '150K+',
    tags: ['Statistics', 'Data Science', 'Probability', 'Data Analysis'],
    skills: ['Statistical Analysis', 'Probability', 'Data Interpretation', 'Research Methods'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Public Speaking and Presentation Skills',
    description: 'Overcome stage fright and become a confident speaker. Learn to structure presentations, engage audiences, use body language effectively, and deliver impactful speeches.',
    platform: 'YouTube',
    category: 'Personal Development',
    subcategory: 'Communication',
    difficulty: 'Beginner',
    duration: '2 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=Zzydx_l-Ask',
    instructor: 'Improvement Pill',
    rating: 4.7,
    studentsEnrolled: '500K+',
    tags: ['Public Speaking', 'Presentation', 'Communication', 'Confidence'],
    skills: ['Public Speaking', 'Presentation Design', 'Communication', 'Confidence Building'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },
  {
    title: 'Photography Basics - Complete Course',
    description: 'Learn photography fundamentals including camera settings, composition, lighting, and editing. Perfect for beginners wanting to improve their photography skills.',
    platform: 'YouTube',
    category: 'Creative Arts',
    subcategory: 'Photography',
    difficulty: 'Beginner',
    duration: '3 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=LxO-6rlihSg',
    instructor: 'Peter McKinnon',
    rating: 4.8,
    studentsEnrolled: '2M+',
    tags: ['Photography', 'Camera', 'Composition', 'Visual Arts'],
    skills: ['Photography', 'Visual Composition', 'Photo Editing', 'Lighting'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },

  // ============================================
  // ADVANCED COMPUTER SCIENCE COURSES
  // ============================================

  // BLOCKCHAIN & WEB3 COURSES
  {
    title: 'Blockchain Full Course - 4 Hours',
    description: 'Comprehensive blockchain tutorial covering fundamentals, cryptocurrency, smart contracts, Ethereum, Solidity programming, and DApp development. Build real blockchain projects from scratch.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Blockchain',
    difficulty: 'Intermediate',
    duration: '4 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=gyMwXuJrbJQ',
    instructor: 'freeCodeCamp.org',
    rating: 4.8,
    studentsEnrolled: '2M+',
    tags: ['Blockchain', 'Cryptocurrency', 'Ethereum', 'Smart Contracts', 'Solidity'],
    skills: ['Blockchain Development', 'Smart Contracts', 'Cryptocurrency', 'Web3'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Solidity, Blockchain, and Smart Contract Course',
    description: 'Learn Solidity programming and smart contract development on Ethereum. Build DeFi applications, NFT marketplaces, and deploy to blockchain. Comprehensive 32-hour course.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Blockchain',
    difficulty: 'Advanced',
    duration: '32 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=umepbfKp5rI',
    instructor: 'freeCodeCamp.org',
    rating: 4.9,
    studentsEnrolled: '800K+',
    tags: ['Solidity', 'Smart Contracts', 'Ethereum', 'DeFi', 'NFT', 'Web3'],
    skills: ['Solidity Programming', 'Smart Contract Development', 'DeFi', 'Web3 Development'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Web3 and Blockchain Full Course',
    description: 'Master Web3 development with blockchain integration. Learn to build decentralized applications using React, ethers.js, and connect to Ethereum networks. Build full-stack DApps.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Blockchain',
    difficulty: 'Intermediate',
    duration: '16 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=M576WGiDBdQ',
    instructor: 'freeCodeCamp.org',
    rating: 4.8,
    studentsEnrolled: '500K+',
    tags: ['Web3', 'Blockchain', 'DApp', 'Ethereum', 'React', 'JavaScript'],
    skills: ['Web3 Development', 'DApp Development', 'Blockchain Integration', 'Frontend Development'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },

  // AI & LLM COURSES
  {
    title: 'LangChain for LLM Application Development',
    description: 'Learn to build LLM applications with LangChain from its creator Harrison Chase. Covers models, prompts, memory, chains, and agents. Build production-ready AI applications.',
    platform: 'DeepLearning.AI',
    category: 'Technology',
    subcategory: 'Artificial Intelligence',
    difficulty: 'Intermediate',
    duration: '1 hour',
    language: 'English',
    courseUrl: 'https://www.deeplearning.ai/short-courses/langchain-for-llm-application-development/',
    instructor: 'Harrison Chase & Andrew Ng',
    rating: 4.9,
    studentsEnrolled: '500K+',
    tags: ['LangChain', 'LLM', 'AI', 'OpenAI', 'GPT', 'Agents'],
    skills: ['LangChain', 'LLM Development', 'AI Applications', 'Prompt Engineering'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Building Applications with Vector Databases',
    description: 'Learn to create AI applications using vector databases with Pinecone. Build semantic search, recommender systems, and RAG applications. Covers embeddings and similarity search.',
    platform: 'DeepLearning.AI',
    category: 'Technology',
    subcategory: 'Artificial Intelligence',
    difficulty: 'Intermediate',
    duration: '1 hour',
    language: 'English',
    courseUrl: 'https://www.deeplearning.ai/short-courses/building-applications-vector-databases/',
    instructor: 'DeepLearning.AI',
    rating: 4.8,
    studentsEnrolled: '200K+',
    tags: ['Vector Databases', 'AI', 'Embeddings', 'Semantic Search', 'RAG'],
    skills: ['Vector Databases', 'Embeddings', 'Semantic Search', 'RAG Systems'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'LangChain & Vector Databases in Production',
    description: 'Free comprehensive course by Activeloop covering LangChain, vector databases, and LLM applications. 50+ lessons with 10+ projects. Learn RAG, embeddings, and production deployment.',
    platform: 'Activeloop',
    category: 'Technology',
    subcategory: 'Artificial Intelligence',
    difficulty: 'Advanced',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://learn.activeloop.ai/courses/langchain',
    instructor: 'Activeloop & Towards AI',
    rating: 4.9,
    studentsEnrolled: '300K+',
    tags: ['LangChain', 'Vector Databases', 'LLM', 'RAG', 'Production AI', 'Deep Lake'],
    skills: ['LangChain', 'Vector Databases', 'Production AI', 'RAG Implementation'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Retrieval Augmented Generation (RAG)',
    description: 'Master RAG systems from DeepLearning.AI. Learn to build production-ready RAG pipelines with vector databases, retrievers, and LLMs. Includes evaluation and optimization techniques.',
    platform: 'DeepLearning.AI',
    category: 'Technology',
    subcategory: 'Artificial Intelligence',
    difficulty: 'Advanced',
    duration: '5 hours',
    language: 'English',
    courseUrl: 'https://learn.deeplearning.ai/courses/retrieval-augmented-generation/',
    instructor: 'Zain Hasan',
    rating: 4.9,
    studentsEnrolled: '150K+',
    tags: ['RAG', 'Vector Databases', 'LLM', 'AI', 'Semantic Search', 'Retrieval'],
    skills: ['RAG Systems', 'Vector Databases', 'Information Retrieval', 'LLM Applications'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Large Language Models with Semantic Search',
    description: 'Learn to enhance LLM applications with semantic search. Build AI systems that retrieve relevant information using embeddings and vector databases. Practical hands-on course.',
    platform: 'DeepLearning.AI',
    category: 'Technology',
    subcategory: 'Artificial Intelligence',
    difficulty: 'Intermediate',
    duration: '1 hour',
    language: 'English',
    courseUrl: 'https://www.deeplearning.ai/short-courses/large-language-models-semantic-search/',
    instructor: 'DeepLearning.AI',
    rating: 4.8,
    studentsEnrolled: '180K+',
    tags: ['LLM', 'Semantic Search', 'Embeddings', 'AI', 'NLP'],
    skills: ['Semantic Search', 'Embeddings', 'LLM Integration', 'Information Retrieval'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },
  {
    title: 'Prompt Engineering for Developers',
    description: 'Learn prompt engineering best practices from OpenAI and DeepLearning.AI. Master techniques for building AI applications with GPT models. Covers summarization, inference, and chatbots.',
    platform: 'DeepLearning.AI',
    category: 'Technology',
    subcategory: 'Artificial Intelligence',
    difficulty: 'Beginner',
    duration: '1 hour',
    language: 'English',
    courseUrl: 'https://www.deeplearning.ai/short-courses/chatgpt-prompt-engineering-for-developers/',
    instructor: 'Isa Fulford & Andrew Ng',
    rating: 4.9,
    studentsEnrolled: '1M+',
    tags: ['Prompt Engineering', 'GPT', 'OpenAI', 'AI', 'LLM'],
    skills: ['Prompt Engineering', 'AI Application Development', 'GPT Models', 'Chatbot Development'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Fine-Tuning Large Language Models',
    description: 'Learn to fine-tune LLMs for specific tasks. Covers data preparation, training techniques, and evaluation. Build customized AI models for your applications.',
    platform: 'DeepLearning.AI',
    category: 'Technology',
    subcategory: 'Artificial Intelligence',
    difficulty: 'Advanced',
    duration: '1 hour',
    language: 'English',
    courseUrl: 'https://www.deeplearning.ai/short-courses/finetuning-large-language-models/',
    instructor: 'DeepLearning.AI',
    rating: 4.8,
    studentsEnrolled: '120K+',
    tags: ['LLM', 'Fine-Tuning', 'AI', 'Machine Learning', 'Model Training'],
    skills: ['LLM Fine-Tuning', 'Model Training', 'AI Customization', 'Transfer Learning'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Building Generative AI Applications with Gradio',
    description: 'Learn to build and deploy AI applications with Gradio. Create interactive demos for LLMs, image generation, and more. Share your AI projects easily.',
    platform: 'DeepLearning.AI',
    category: 'Technology',
    subcategory: 'Artificial Intelligence',
    difficulty: 'Beginner',
    duration: '1 hour',
    language: 'English',
    courseUrl: 'https://www.deeplearning.ai/short-courses/building-generative-ai-applications-with-gradio/',
    instructor: 'DeepLearning.AI',
    rating: 4.7,
    studentsEnrolled: '100K+',
    tags: ['Gradio', 'AI', 'LLM', 'Image Generation', 'UI Development'],
    skills: ['Gradio', 'AI Application Development', 'UI Design', 'Model Deployment'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },

  // DEVOPS & CLOUD COURSES
  {
    title: 'Kubernetes Course - Full Beginners Tutorial',
    description: 'Complete Kubernetes tutorial covering containers, pods, deployments, services, and cluster management. Learn container orchestration and deploy applications to production.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'DevOps',
    difficulty: 'Intermediate',
    duration: '4 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=X48VuDVv0do',
    instructor: 'TechWorld with Nana',
    rating: 4.9,
    studentsEnrolled: '3M+',
    tags: ['Kubernetes', 'DevOps', 'Containers', 'Docker', 'Cloud', 'Orchestration'],
    skills: ['Kubernetes', 'Container Orchestration', 'DevOps', 'Cloud Deployment'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Complete DevOps Course',
    description: 'Learn DevOps fundamentals including Linux, Git, Docker, Kubernetes, CI/CD, Jenkins, Terraform, and cloud platforms. Comprehensive course for DevOps engineers.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'DevOps',
    difficulty: 'Intermediate',
    duration: '9 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=j5Zsa_eOXeY',
    instructor: 'KodeKloud',
    rating: 4.8,
    studentsEnrolled: '1M+',
    tags: ['DevOps', 'Docker', 'Kubernetes', 'CI/CD', 'Jenkins', 'Terraform'],
    skills: ['DevOps', 'Automation', 'CI/CD', 'Cloud Infrastructure', 'Container Management'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Terraform Course - Automate Infrastructure',
    description: 'Learn Infrastructure as Code with Terraform. Automate cloud infrastructure deployment on AWS, Azure, and GCP. Master Terraform configurations and best practices.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'DevOps',
    difficulty: 'Intermediate',
    duration: '5 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=SLB_c_ayRMo',
    instructor: 'freeCodeCamp.org',
    rating: 4.8,
    studentsEnrolled: '800K+',
    tags: ['Terraform', 'Infrastructure as Code', 'DevOps', 'AWS', 'Cloud', 'Automation'],
    skills: ['Terraform', 'Infrastructure as Code', 'Cloud Automation', 'DevOps'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },
  {
    title: 'Jenkins Tutorial - CI/CD Pipeline',
    description: 'Complete Jenkins course for continuous integration and deployment. Learn to build automated CI/CD pipelines, integrate with Git, Docker, and Kubernetes.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'DevOps',
    difficulty: 'Intermediate',
    duration: '3 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=7KCS70sCoK0',
    instructor: 'Simplilearn',
    rating: 4.7,
    studentsEnrolled: '600K+',
    tags: ['Jenkins', 'CI/CD', 'DevOps', 'Automation', 'Pipeline', 'Testing'],
    skills: ['Jenkins', 'CI/CD', 'Build Automation', 'DevOps Pipelines'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },
  {
    title: 'Ansible Full Course',
    description: 'Master Ansible for automation and configuration management. Learn playbooks, roles, inventory management, and automate infrastructure deployment across multiple servers.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'DevOps',
    difficulty: 'Intermediate',
    duration: '3 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=9Ua2b06oAr4',
    instructor: 'TechWorld with Nana',
    rating: 4.8,
    studentsEnrolled: '500K+',
    tags: ['Ansible', 'Automation', 'Configuration Management', 'DevOps', 'Infrastructure'],
    skills: ['Ansible', 'Automation', 'Configuration Management', 'Infrastructure as Code'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },

  // NETWORKING COURSES
  {
    title: 'CCNA 200-301 Complete Course',
    description: 'Full CCNA certification preparation course. Learn networking fundamentals, routing, switching, IP addressing, network security, and wireless networking. Industry-standard certification.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Networking',
    difficulty: 'Intermediate',
    duration: '19 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=rv3QK2UquxM',
    instructor: "Jeremy's IT Lab",
    rating: 4.9,
    studentsEnrolled: '1M+',
    tags: ['CCNA', 'Networking', 'Cisco', 'Routing', 'Switching', 'Network Security'],
    skills: ['Networking', 'Routing and Switching', 'Network Configuration', 'Cisco IOS'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Computer Networking Course',
    description: 'Comprehensive networking course covering OSI model, TCP/IP, protocols, network devices, subnetting, and network troubleshooting. Essential for IT professionals.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Networking',
    difficulty: 'Beginner',
    duration: '9 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=qiQR5rTSshw',
    instructor: 'freeCodeCamp.org',
    rating: 4.8,
    studentsEnrolled: '2M+',
    tags: ['Networking', 'TCP/IP', 'OSI Model', 'Protocols', 'Subnetting'],
    skills: ['Networking Fundamentals', 'Protocol Analysis', 'Network Troubleshooting', 'IP Addressing'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Network Programming with Python',
    description: 'Learn network programming and automation with Python. Build network tools, automate network tasks, and work with protocols. Perfect for network engineers and DevOps.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Networking',
    difficulty: 'Intermediate',
    duration: '5 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=FGdiSJakIS4',
    instructor: 'freeCodeCamp.org',
    rating: 4.7,
    studentsEnrolled: '400K+',
    tags: ['Python', 'Network Programming', 'Automation', 'Networking', 'DevOps'],
    skills: ['Network Programming', 'Python', 'Network Automation', 'Protocol Implementation'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },

  // COMPUTER HARDWARE & SYSTEMS
  {
    title: 'Computer Hardware Basics',
    description: 'Learn computer hardware fundamentals from Cisco. Covers components, assembly, maintenance, and troubleshooting. Essential knowledge for IT support and hardware technicians.',
    platform: 'Cisco Networking Academy',
    category: 'Technology',
    subcategory: 'Hardware',
    difficulty: 'Beginner',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://www.netacad.com/courses/computer-hardware-basics',
    instructor: 'Cisco',
    rating: 4.6,
    studentsEnrolled: '500K+',
    tags: ['Hardware', 'Computer Components', 'Troubleshooting', 'IT Support'],
    skills: ['Hardware Knowledge', 'Computer Assembly', 'Troubleshooting', 'Component Identification'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },
  {
    title: 'PC Hardware Course - Carnegie Mellon OLI',
    description: 'Free comprehensive PC hardware course covering system board, processors, memory, storage, and peripherals. Aligned with CompTIA A+ certification. University-level content.',
    platform: 'Carnegie Mellon OLI',
    category: 'Technology',
    subcategory: 'Hardware',
    difficulty: 'Beginner',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://oli.cmu.edu/courses/pc-hardware-open-free/',
    instructor: 'Carnegie Mellon University',
    rating: 4.7,
    studentsEnrolled: '200K+',
    tags: ['Hardware', 'PC Components', 'CompTIA A+', 'Troubleshooting', 'Assembly'],
    skills: ['Hardware Assembly', 'System Maintenance', 'Troubleshooting', 'Component Configuration'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },
  {
    title: 'Computer Architecture',
    description: 'Learn how computers work at the hardware level. Covers processors, memory hierarchy, instruction sets, pipelining, and system design. Essential for computer engineers.',
    platform: 'MIT OpenCourseWare',
    category: 'Technology',
    subcategory: 'Computer Science',
    difficulty: 'Advanced',
    duration: 'Self-paced',
    language: 'English',
    courseUrl: 'https://ocw.mit.edu/courses/6-004-computation-structures-spring-2017/',
    instructor: 'MIT',
    rating: 4.8,
    studentsEnrolled: '300K+',
    tags: ['Computer Architecture', 'Hardware', 'Processors', 'System Design', 'MIT'],
    skills: ['Computer Architecture', 'System Design', 'Hardware Engineering', 'Low-Level Programming'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Digital Systems and Computer Architecture',
    description: 'Learn digital logic, circuit design, processor architecture, and assembly language. Build understanding from transistors to full computer systems.',
    platform: 'Alison',
    category: 'Technology',
    subcategory: 'Hardware',
    difficulty: 'Intermediate',
    duration: '3-4 hours',
    language: 'English',
    courseUrl: 'https://alison.com/course/introduction-to-computer-hardware-and-software',
    instructor: 'Alison',
    rating: 4.5,
    studentsEnrolled: '150K+',
    tags: ['Digital Systems', 'Computer Architecture', 'Hardware', 'Logic Design'],
    skills: ['Digital Logic', 'Computer Architecture', 'Circuit Design', 'Assembly Language'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },

  // AUTOMATION & NO-CODE
  {
    title: 'n8n Automation Tutorial',
    description: 'Learn n8n workflow automation. Build AI agents, automate business processes, integrate APIs without code. Create powerful automation workflows visually.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Automation',
    difficulty: 'Beginner',
    duration: '2 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/results?search_query=n8n+tutorial+complete',
    instructor: 'Various Creators',
    rating: 4.7,
    studentsEnrolled: '100K+',
    tags: ['n8n', 'Automation', 'No-Code', 'Workflow', 'AI Agents', 'Integration'],
    skills: ['Workflow Automation', 'No-Code Development', 'API Integration', 'Process Automation'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },
  {
    title: 'Build AI Agents with n8n',
    description: 'Create AI-powered automation agents using n8n. Integrate LLMs, build chatbots, automate complex workflows with AI. No coding required for powerful AI solutions.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Artificial Intelligence',
    difficulty: 'Intermediate',
    duration: '3 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/results?search_query=n8n+ai+agents+tutorial',
    instructor: 'Various Creators',
    rating: 4.8,
    studentsEnrolled: '80K+',
    tags: ['n8n', 'AI Agents', 'Automation', 'LLM', 'Chatbots', 'No-Code'],
    skills: ['AI Automation', 'Agent Building', 'Workflow Design', 'LLM Integration'],
    isFree: true,
    isVerified: true,
    isFeatured: false
  },

  // ADVANCED PROGRAMMING & SYSTEMS
  {
    title: 'Rust Programming Course',
    description: 'Learn Rust systems programming language. Covers ownership, borrowing, memory safety, concurrency, and building high-performance applications. Modern systems programming.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Programming',
    difficulty: 'Advanced',
    duration: '15 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=BpPEoZW5IiY',
    instructor: 'freeCodeCamp.org',
    rating: 4.9,
    studentsEnrolled: '500K+',
    tags: ['Rust', 'Systems Programming', 'Memory Safety', 'Concurrency', 'Performance'],
    skills: ['Rust Programming', 'Systems Programming', 'Memory Management', 'Concurrent Programming'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'Go Programming Full Course',
    description: 'Complete Golang tutorial from basics to advanced. Learn concurrent programming, web development, and building scalable backend systems with Go.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'Programming',
    difficulty: 'Intermediate',
    duration: '7 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=YS4e4q9oBaU',
    instructor: 'freeCodeCamp.org',
    rating: 4.8,
    studentsEnrolled: '1M+',
    tags: ['Go', 'Golang', 'Backend', 'Concurrency', 'Systems Programming'],
    skills: ['Go Programming', 'Concurrent Programming', 'Backend Development', 'Microservices'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
  {
    title: 'System Design Course',
    description: 'Learn to design large-scale distributed systems. Covers scalability, load balancing, caching, databases, microservices, and system architecture. Essential for senior engineers.',
    platform: 'YouTube',
    category: 'Technology',
    subcategory: 'System Design',
    difficulty: 'Advanced',
    duration: '10 hours',
    language: 'English',
    courseUrl: 'https://www.youtube.com/watch?v=F2FmTdLtb_4',
    instructor: 'freeCodeCamp.org',
    rating: 4.9,
    studentsEnrolled: '800K+',
    tags: ['System Design', 'Architecture', 'Scalability', 'Distributed Systems', 'Microservices'],
    skills: ['System Design', 'Architecture Design', 'Scalability', 'Distributed Systems'],
    isFree: true,
    isVerified: true,
    isFeatured: true
  },
];

const seedDatabase = async () => {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ MongoDB connected');

    // Clear existing data
    await Course.deleteMany();
    console.log('🗑️  Cleared existing courses');

    // Insert sample courses
    await Course.insertMany(courses);
    console.log(`✅ Added ${courses.length} completely FREE courses for COLLEGE STUDENTS!`);
    console.log('📚 Platforms: freeCodeCamp, YouTube, edX, MIT OCW, Saylor Academy, GeeksforGeeks, Scaler, Alison');
    console.log('🎓 Many courses offer FREE certificates!');
    console.log('🚫 Removed all Coursera courses (audit mode not truly free)');
    
    console.log('\n📊 Course Breakdown by Platform:');
    console.log(`   - freeCodeCamp: 3 courses (FREE certificates)`);
    console.log(`   - YouTube: 17 courses`);
    console.log(`   - edX: 6 courses (FREE certificates)`);
    console.log(`   - MIT OpenCourseWare: 5 courses (World-class education)`);
    console.log(`   - Saylor Academy: 10 courses (FREE certificates)`);
    console.log(`   - GeeksforGeeks: 2 courses`);
    console.log(`   - Scaler Topics: 3 courses`);
    console.log(`   - Alison: 1 course`);
    
    console.log('\n🎯 Domains Covered:');
    console.log(`   - Technology & Computer Science`);
    console.log(`   - Business & Management`);
    console.log(`   - Economics & Finance`);
    console.log(`   - Psychology & Social Science`);
    console.log(`   - Mathematics & Statistics`);
    console.log(`   - Communication & Soft Skills`);
    console.log(`   - Creative Arts & Photography`);
    console.log(`   - Environmental Science`);
    
    console.log('\n🎉 Database seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
};

seedDatabase();